@URL = http://localhost:5000/api/

## Character

### Query all characters

GET {{URL}}character/

### Query a character by id

GET {{URL}}character/2445

### Create a new character

POST {{URL}}character/
Content-Type: application/json

{
  "name": "夏目藍",
  "romaji": "Natsume Ai",
  "gender": "FEMALE",
  "alias": ["夏目蓝", "蓝姐"],
  "images": ["https://img.moegirl.org.cn/common/thumb/d/dd/Ai-now3.png/280px-Ai-now3.png"],
  "url": ["https://mzh.moegirl.org.cn/%E5%A4%8F%E7%9B%AE%E8%93%9D"],
  "description": "虽然有时看起来是个迷迷糊糊的冒失娘，但实际上直觉却相当敏锐，对包括主角在内的大家抱有极强的责任心。",
  "comment": "陪伴是最长情的告白，而爱情则是最美好的结局。",
  "hitokoto": "请一定要活的比我长寿，请为我送终，我不想再为我最爱的家人送终了",
  "birthday": 998668800000,
  "voice": "泽田夏",
  "series": "サクラノ詩－櫻の森の上を舞う－",
  "seriesGenre": "GALGAME",
  "hairColor": "黑发",
  "height": 145,
  "bust": 77,
  "waist": 56,
  "hip": 76,
  "tags": ["姐姐", "合法萝莉", "老师", "黑长直", "小姨", "心形瞳孔"]
}

### Update a character by id

PUT {{URL}}character/22
Content-Type: application/json

### Delete a character by id

DELETE {{URL}}character/5232

## Serie

### Query all series

GET {{URL}}series

## Tags

### Query all tags

GET {{URL}}tag

## Collection

### Query all collections

GET {{URL}}collection

### Query a collection by id

GET {{URL}}collection/123232

### Create a new collection

POST {{URL}}collection/
Content-Type: application/json

{
  "name": "co1",
  "description": "descr..."
}

### Update a collection by id

PUT {{URL}}collection/1
Content-Type: application/json

{
  "name": "co1",
  "description": "descr...",
  "characters": [4, 1]
}

### Delete a collection by id

DELETE {{URL}}collection/1

### Get all settings

GET {{URL}}settings

### Update settings